# Generated by Django 5.2.4 on 2026-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_max_uses_coupon_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
